package medrex.commons.enums;

/**
 * @author D S Naruka
 */
public enum SubAppTypes {
	/* enum constants */
	CNA(1), CARELOG(2), MEDICATION_CART(3), REPORTS(4), PROVIDERS(5), CENSUS(6), ADMISSION_RECORDS(
			7), ACTIVITY(8), MEDICATION_TREATMENT(9), DIETARY(10), CONSULTANT(
			11), PROGRESS_NOTES(12), LAB_SPECIAL_REPORTS(13), HISTORY_PHYSICAL(
			14), PHYSICIAN_ORDERS(15), OTPTACT_SPEECH(16), MDS(17), CARE_PLAN(
			18), ALERT(18)/* , MDS_PENDING(18) */, MONTHLY_SUMMARY(19), DIALYSIS_RECORDS(
			22), NURSES_NOTES_RECORDS(23)
	// suresh
	, MAIN_RESIDENT(33), USERS(34), USERLOGON(35), MESSAGES(36), MASTERLIST(37), ADMIN(
			38)

	, RESIDENT_INFORMATION_ALLERGIES(19), RESIDENT_INFORMATION_SCHEDULING(20), RESIDENT_INFORMATION_VITAL(
			21), RESIDENT_INFORMATION_WEIGHT(22), RESIDENT_INFORMATION_WOUNDS(
			23), RESIDENT_INFORMATION_PERSONALINFO(24), RESIDENT_INFORMATION_PAYERINFO(
			25), RESIDENT_INFORMATION_CONTACTINFO(26), RESIDENT_INFORMATION_PHYSICIAN(
			27), RESIDENT_INFORMATION_PROVIDERS(28), RESIDENT_INFORMATION_CENSUS(
			29), RESIDENT_INFORMATION_DIAGNOSIS(30), RESIDENT_INFORMATION_SCAN(
			31), RESIDENT_INFORMATION_ROOM(32);

	/* enum fields */
	public final int ID;

	SubAppTypes(int id) {
		this.ID = id;

	}

	// public List<JPanel> getForms() {
	// return forms;
	// }
	//
	// public void setForms(List<JPanel> forms) {
	// this.forms = forms;
	// }

	// public void addForm(JPanel p) {
	// getForms().add(p);
	// }
}
